- 👋 Hi, I’m @shaniaaa0
- 👀 I’m interested in ...
- 🌱 I’m currently learning ...
- 💞️ I’m looking to collaborate on ...
- 📫 How to reach me ...
- 😄 Pronouns: ...
- ⚡ Fun fact: ...

<!---
shaniaaa0/shaniaaa0 is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
# Student Information  
- Name: [Sania Sabir]  
- Roll Number: [B-29593]  
- Lab Task: GitHub Repository and Branching  
